name: Vercel Production Deployment
on:
  push:
    branches:
      - main
      - vercel
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    environment: production
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Set Vercel Environment Variables
        run: |
          vercel env add HTTP_PORT ${{ secrets.HTTP_PORT }} --environment=production --token ${{ secrets.VERCEL_TOKEN }}
          vercel env add REDMINE_URL ${{ secrets.REDMINE_URL }} --environment=production --token ${{ secrets.VERCEL_TOKEN }}
          vercel env add REDMINE_API_KEY ${{ secrets.REDMINE_API_KEY }} --environment=production --token ${{ secrets.VERCEL_TOKEN }}
          vercel env add GITLAB_URL ${{ secrets.GITLAB_URL }} --environment=production --token ${{ secrets.VERCEL_TOKEN }}
          vercel env add GITLAB_API_KEY ${{ secrets.GITLAB_API_KEY }} --environment=production --token ${{ secrets.VERCEL_TOKEN }}
          vercel env add GITHUB_URL ${{ secrets.GH_URL }} --environment=production --token ${{ secrets.VERCEL_TOKEN }}
          vercel env add GITHUB_API_KEY ${{ secrets.GH_API_KEY }} --environment=production --token ${{ secrets.VERCEL_TOKEN }}

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
